// <auto-generated />
using HomeImprovementShopCartBlazor.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeImprovementShopCartBlazor.API.Migrations
{
    [DbContext(typeof(HomeImprovementShopCartDbContext))]
    partial class HomeImprovementShopCartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeImprovementShopCartBlazor.API.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("HomeImprovementShopCartBlazor.API.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("HomeImprovementShopCartBlazor.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A kitchen provided by Glossy, with Quartz countertop and oak wood",
                            ImageURL = "/Images/Kitchen/img1.jpg",
                            Name = "Glossy - Granite",
                            Price = 100m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "A kitchen provided by Curology, with Granite countertop and oak wood",
                            ImageURL = "/Images/Kitchen/img2.jpg",
                            Name = "Curology - Granit",
                            Price = 50m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = " spacious islands are partly to blame for wall units falling out of fashion",
                            ImageURL = "/Images/Kitchen/img3.jpg",
                            Name = "Cocooil - Quartz",
                            Price = 20m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Popular options include lift up doors and tall, sleek, flat-fronted doors in a striking material",
                            ImageURL = "/Images/Kitchen/img4.jpg",
                            Name = "Schwarzkopf - Open plan kitchens",
                            Price = 50m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Modern galley kitchens can be part of a much larger space, featuring a wall-hugging galley run with a long island running parallel",
                            ImageURL = "/Images/Kitchen/img5.jpg",
                            Name = "Third galley kitchen",
                            Price = 30m,
                            Qty = 85
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Air Pods - in-ear wireless headphones",
                            ImageURL = "/Images/Kitchen/img6.jpg",
                            Name = "Air Pods",
                            Price = 100m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "A scheme that includes plenty of storage, and if wall units aren’t possible in all areas",
                            ImageURL = "/Images/Kitchen/img7.jpg",
                            Name = "Declutter The Right Storage",
                            Price = 40m,
                            Qty = 200
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "The trick is to make the space work for you – make it look bigger by using light colors and reflective surfaces",
                            ImageURL = "/Images/Kitchen/img8.jpg",
                            Name = "Minimal Cabinetry",
                            Price = 40m,
                            Qty = 300
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = " one of the most intelligent types of bed design as they can be pushed back into the wall when not in use",
                            ImageURL = "/Images/Bedroom/img1.jpg",
                            Name = "Murphy Bed",
                            Price = 600m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "ow bed which can be pulled out or rolled out from the parent bed or bed with sliders.",
                            ImageURL = "/Images/Bedroom/img2.jpg",
                            Name = "Trundle Bed",
                            Price = 500m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "the most popular choice when thinking of  beds for children’s rooms",
                            ImageURL = "/Images/Bedroom/img3.jpg",
                            Name = "Bunk Beds",
                            Price = 100m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "This box type bed design has a lift-up mechanism and is built to provide storage beneath",
                            ImageURL = "/Images/Bedroom/img4.jpg",
                            Name = "Hydraulic Beds",
                            Price = 50m,
                            Qty = 212
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Floor beds are often called futons that are nothing but padded mattresses and are easy to roll up",
                            ImageURL = "/Images/Bedroom/img5.jpg",
                            Name = "Floor Bed",
                            Price = 50m,
                            Qty = 112
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = " bed which have storage either to lift up or in the form of drawer type bed.",
                            ImageURL = "/Images/Bedroom/img6.jpg",
                            Name = "Storage Bed",
                            Price = 70m,
                            Qty = 90
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "These bathrooms can feature one or two sinks, and include a tub or shower and a toilet",
                            ImageURL = "/Images/Bathroom/img1.jpg",
                            Name = "Jack-and-Jill",
                            Price = 120m,
                            Qty = 95
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Split bathrooms are ideal in situations where the bathroom has to be shared by more than one person",
                            ImageURL = "/Images/Bathroom/img2.jpg",
                            Name = "Split/Split Entry",
                            Price = 15m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "They feature a shower stall that can either be placed in the corner for the best use of space",
                            ImageURL = "/Images/Bathroom/img3.jpg",
                            Name = "Corner Shower",
                            Price = 20m,
                            Qty = 73
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Sufficiently clear floor space so that a wheelchair is able to perform a complete turn",
                            ImageURL = "/Images/Bathroom/img4.jpg",
                            Name = "Accessible Residential",
                            Price = 100m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "entry area and main or primary sink in one distinct area of the bathroom",
                            ImageURL = "/Images/Bathroom/img5.jpg",
                            Name = "Colorful Style",
                            Price = 150m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "One might also see this bathroom referred to as the primary bathroom",
                            ImageURL = "/Images/Bathroom/img6.jpg",
                            Name = "Blue Nike Style",
                            Price = 200m,
                            Qty = 70
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Strategically placed storage shelves, and although still widely considered",
                            ImageURL = "/Images/Bathroom/img7.jpg",
                            Name = "Three-Quarter",
                            Price = 120m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "materials that are slip-resistant as well as mold- and mildew-resistant are ideal.",
                            ImageURL = "/Images/Bathroom/img8.jpg",
                            Name = "Shelving and art",
                            Price = 200m,
                            Qty = 100
                        });
                });

            modelBuilder.Entity("HomeImprovementShopCartBlazor.API.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconCSS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconCSS = "fas fa-sink",
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 2,
                            IconCSS = "fas fa-bed",
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 3,
                            IconCSS = "fas fa-restroom",
                            Name = "Bathroom"
                        },
                        new
                        {
                            Id = 4,
                            IconCSS = "fas fa-shoe-prints",
                            Name = "Shoes"
                        });
                });

            modelBuilder.Entity("HomeImprovementShopCartBlazor.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Shazia"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Idrees"
                        });
                });

            modelBuilder.Entity("HomeImprovementShopCartBlazor.API.Entities.Product", b =>
                {
                    b.HasOne("HomeImprovementShopCartBlazor.API.Entities.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
